# -*- coding: utf-8 -*-
"""SHONA-SENT XLMR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IJC9omK-PWhzJ_yDZTD6Z8Dwuc_qGjt
"""

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NO GPU")

from google.colab import files

uploaded = files.upload()

!python /content/SHONA_SENT_Framework_Implementation_V6_FIXED.py

from google.colab import files
files.download('/content/SHONA_SENT_Experiment_Results.zip')